services:
  frontend:
    build:
      context: .
      args:
        BUILD_CONFIGURATION: e2e
    image: messenger-frontend:e2e
    ports:
      - '8080:80'

  mock-auth-backend:
    build:
      context: ./mock-auth-backend
    image: messenger-mock-auth-backend:e2e
    ports:
      - '3000:3000'
