all:
  children:
    current_server:
      hosts:
        koara_current:
          ansible_host: 73053.koara.live
          ansible_user: deploy

    fastvps_bootstrap:
      hosts:
        fastvps_new:
          ansible_host: s9865e4c2.fastvps-server.com
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3

    fastvps_managed:
      hosts:
        fastvps_new_managed:
          ansible_host: s9865e4c2.fastvps-server.com
          ansible_user: deploy
          ansible_python_interpreter: /usr/bin/python3
